### ISSUE TITLE
Dot at beginning of cookie domain field isn't ignored (results in `DomainMismatch` error)

### ISSUE THREAD

**Issue by d4h0** [pfernie/cookie_store#34]
Hi,

As mentioned in the title, a domain with leading dot isn't handled properly (“properly” meaning "as browser seem to handle it"):

```rust
let mut cs = cookie_store::CookieStore::load_json(b"".as_slice()).unwrap();

// No leading dot => works:
let c = cookie::Cookie::build("name", "value")
    .domain("name.com")
    .finish();
cs.insert_raw(
    &c,
    &url::Url::parse("https://subdomain.name.com").unwrap(),
)
.unwrap();

// With leading dot => fails with `cookie_store::CookieError::DomainMismatch`:
let c = cookie::Cookie::build("name", "value")
    .domain(".name.com")
    .finish();
cs.insert_raw(
    &c,
    &url::Url::parse("https://subdomain.name.com").unwrap(),
)
.unwrap();

```

The following article (not mine) has some background information:

[Leading Dots On HTTP Cookie Domains Ignored
](https://www.bennadel.com/blog/4345-leading-dots-on-http-cookie-domains-ignored.htm)

**Comment by pfernie** [comment]
You are right, this [should](https://www.rfc-editor.org/rfc/rfc6265#section-5.2.3) be supported behavior, and in fact the implementation does [support it](https://github.com/pfernie/cookie_store/blob/master/src/cookie_domain.rs#L125-L143). However, in the case we are processing a `cookie:Cookie`, the logic relies on the fact this processing should already [be done](https://github.com/pfernie/cookie_store/blob/master/src/cookie_domain.rs#L145-L169)

So I believe this is actually a change that should happen upstream. If instead of using the `cookie` builder, we parse from a cookie string, the behavior works as expected:

```rust
    let mut cs = cookie_store::CookieStore::load_json(b"".as_slice()).unwrap();
    // No leading dot => works:
    let c = cookie::Cookie::build("name", "value")
        .domain("name.com")
        .finish();
    cs.insert_raw(&c, &url::Url::parse("https://subdomain.name.com").unwrap())
        .unwrap();

    // Leading dot works when using `FromStr` parsing impl => works
    let c = cookie::Cookie::from_str("name=value; Domain=.name.com").unwrap();
    cs.insert_raw(&c, &url::Url::parse("https://subdomain.name.com").unwrap())
        .unwrap();
```

Upstream, we can see the expected logic is implemented [here](https://github.com/SergioBenitez/cookie-rs/blob/master/src/parse.rs#L202-L205) in the string parsing case.

So it seems to me the upstream `builder` behavior should match the upstream string parsing behavior. That is:

```rust
let c1 = cookie::Cookie::from_str("name=value; Domain=name.com").unwrap();
let c2 = cookie::Cookie::build("name", "value")
    .domain("name.com")
    .finish();
// this passes, as we would expect
assert_eq!(c1, c2);

let c1 = cookie::Cookie::from_str("name=value; Domain=.name.com").unwrap();
let c2 = cookie::Cookie::build("name", "value")
    .domain(".name.com")
    .finish();
// this does not
assert_eq!(c1, c2);
```


As mentioned in the `cookie_store` code,  we do not want to do this stripping twice (if it has already been done in the `cookie` implementation), as we expect `Domain=.name.com` attribute to be interpreted differently from `Domain=..name.com` (two leading dots).

**Comment by d4h0** [comment]
That makes sense, thanks @pfernie!

I've opened a new issue in the `cookie-rs` repo: https://github.com/SergioBenitez/cookie-rs/issues/207.
